### ISSUE TITLE
[Issue] Error trying to start the game.

### ISSUE THREAD

**Issue by rabrunos** [AlexModGuy/LocalLooks#4]
### Issue
Minecraft does not start with the mod installed.

### How to reproduce?
Just install the mod along with Citadel and start the game.

### System Info
Minecraft 1.18.2
Forge 40.0.17
Java SDK 17
8GB RAM for Java

Used mods:
[Local Looks 1.2.0 - 1.18.2](https://www.curseforge.com/minecraft/mc-mods/local-looks/files/3694817)
[Citadel 1.11.1 - 1.18.2](https://www.curseforge.com/minecraft/mc-mods/citadel/files/3683007)

### Log files
debug.log file
https://mclo.gs/1mrRO02

lastest.log file
https://mclo.gs/blhjVpy

**Comment by AlexModGuy** [comment]
does the issue happen with just citadel alone?

**Comment by rabrunos** [comment]
No, it only happens when I start together with Local Looks.

**Comment by AlexModGuy** [comment]
should be fixed in this hotfix https://www.curseforge.com/minecraft/mc-mods/local-looks/files/3694903

**Comment by faelBrunnoS** [comment]
I renamed `citadel.mixins.json` to `locallooks.mixins.json` and it worked

**Comment by rabrunos** [comment]
> should be fixed in this hotfix https://www.curseforge.com/minecraft/mc-mods/local-looks/files/3694903

I will test it now then.

**Comment by rabrunos** [comment]
I had renamed `citadel.mixins.json` to `locallooks.mixins.json` and it worked
haha
